WORKING WITH DATASET

In [1]:
import pandas as pd
import numpy as np

In [2]:
superstore_df=pd.read_csv(r"C:\Users\USER\Documents\New folder\my Data\SampleSuperstore.csv")
superstore_df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [19]:
superstore_df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [20]:
superstore_df.shape

(9994, 13)

In [21]:
superstore_df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [23]:
superstore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [26]:
superstore_df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [34]:
print(superstore_df['Category'].unique())

['Furniture' 'Office Supplies' 'Technology']

In [35]:
print(superstore_df['State'].unique())

['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington' 'Texas'
 'Wisconsin' 'Utah' 'Nebraska' 'Pennsylvania' 'Illinois' 'Minnesota'
 'Michigan' 'Delaware' 'Indiana' 'New York' 'Arizona' 'Virginia'
 'Tennessee' 'Alabama' 'South Carolina' 'Oregon' 'Colorado' 'Iowa' 'Ohio'
 'Missouri' 'Oklahoma' 'New Mexico' 'Louisiana' 'Connecticut' 'New Jersey'
 'Massachusetts' 'Georgia' 'Nevada' 'Rhode Island' 'Mississippi'
 'Arkansas' 'Montana' 'New Hampshire' 'Maryland' 'District of Columbia'
 'Kansas' 'Vermont' 'Maine' 'South Dakota' 'Idaho' 'North Dakota'
 'Wyoming' 'West Virginia']

In [38]:
no_of_states= superstore_df['State'].nunique()
print("There are %d states in this df."%no_of_states)

There are 49 states in this df.

In [39]:
print(superstore_df['Sub-Category'].unique())

['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']

In [40]:
no_of_subcategory= superstore_df['Sub-Category'].nunique()
print("Categories are divided into %d subcategories."%no_of_subcategory)

Categories are divided into 17 subcategories.

In [41]:
superstore_df['Segment'].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [42]:
superstore_df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

CREATING LOSS DATAFRAME

In [3]:
loss_df=superstore_df[superstore_df['Profit'] < 0]
loss_df

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
14,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,68.8100,5,0.80,-123.8580
15,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,2.5440,3,0.80,-3.8160
23,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Chairs,71.3720,2,0.30,-1.0196
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.4300,7,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,Standard Class,Corporate,United States,Bryan,Texas,77803,Central,Office Supplies,Binders,22.3860,7,0.80,-35.8176
9921,Standard Class,Home Office,United States,Akron,Ohio,44312,East,Office Supplies,Binders,5.7420,3,0.70,-4.5936
9931,Standard Class,Consumer,United States,San Bernardino,California,92404,West,Furniture,Bookcases,683.3320,4,0.15,-40.1960
9937,Second Class,Corporate,United States,Los Angeles,California,90049,West,Furniture,Tables,71.0880,2,0.20,-1.7772
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704

In [4]:
loss_df.shape

(1871, 13)

In [5]:
loss_df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   1871.000000   1871.000000  1871.000000  1871.000000  1871.000000
mean   55991.122929    250.511574     3.762694     0.480887   -83.448042
std    26041.501999    715.067296     2.141347     0.235080   284.423422
min     1841.000000      0.444000     1.000000     0.100000 -6599.978000
25%    33024.000000     12.503000     2.000000     0.200000   -58.660950
50%    60623.000000     71.088000     3.000000     0.400000   -18.088200
75%    77095.000000    284.922000     5.000000     0.700000    -6.261500
max    98198.000000  22638.480000    14.000000     0.800000    -0.089500

In [48]:
Total_loss=np.negative(loss_df['Profit'].sum())
print("Total loss = %.2f" %Total_loss)

Total loss = 156131.29

In [6]:
loss_df.groupby(by='Segment').sum()

,Ship Mode,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Segment,,,,,,,,,,,,
Consumer,Standard ClassSecond ClassStandard ClassStanda...,United StatesUnited StatesUnited StatesUnited ...,Fort LauderdalePhiladelphiaPhiladelphiaPhilade...,FloridaPennsylvaniaPennsylvaniaPennsylvaniaPen...,57202260,SouthEastEastEastEastSouthSouthCentralWestWest...,FurnitureFurnitureFurnitureOffice SuppliesOffi...,TablesChairsBookcasesBindersBindersChairsStora...,247196.2460,3651,476.76,-84945.7112
Corporate,First ClassFirst ClassFirst ClassStandard Clas...,United StatesUnited StatesUnited StatesUnited ...,RichardsonHoustonHoustonBristolColumbusChicago...,TexasTexasTexasTennesseeOhioIllinoisPennsylvan...,30034273,CentralCentralCentralSouthEastCentralEastEastE...,FurnitureOffice SuppliesFurnitureOffice Suppli...,FurnishingsBindersFurnishingsBindersPhonesAppl...,131860.5383,2191,272.00,-44787.2076
Home Office,Standard ClassStandard ClassStandard ClassStan...,United StatesUnited StatesUnited StatesUnited ...,Fort WorthFort WorthHoustonHoustonChicagoChica...,TexasTexasTexasTexasIllinoisIllinoisOregonIlli...,17522858,CentralCentralCentralCentralCentralCentralWest...,Office SuppliesOffice SuppliesFurnitureFurnitu...,AppliancesBindersBookcasesChairsChairsStorageB...,89650.3705,1198,150.98,-26398.3669

##### * more discount leads to more loss,so,to make profit provide fewer discounts

In [7]:
loss_df.groupby(by="Sub-Category").sum()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sales,Quantity,Discount,Profit
Sub-Category,,,,,,,,,,,,
Accessories,Standard ClassStandard ClassStandard ClassStan...,Home OfficeConsumerHome OfficeConsumerConsumer...,United StatesUnited StatesUnited StatesUnited ...,ChicagoAuroraTampaTucsonPembroke PinesJacksonv...,IllinoisColoradoFloridaArizonaFloridaFloridaOh...,5286382,CentralWestSouthWestSouthSouthEastCentralWestW...,TechnologyTechnologyTechnologyTechnologyTechno...,10958.8000,330,18.20,-930.6265
Appliances,Standard ClassStandard ClassStandard ClassSeco...,Home OfficeConsumerCorporateConsumerConsumerCo...,United StatesUnited StatesUnited StatesUnited ...,Fort WorthSan AntonioChicagoHoustonDallasPasad...,TexasTexasIllinoisTexasTexasTexasTexasTexasIll...,4825871,CentralCentralCentralCentralCentralCentralCent...,Office SuppliesOffice SuppliesOffice SuppliesO...,3382.5340,235,53.60,-8629.6412
Binders,Standard ClassStandard ClassStandard ClassFirs...,Home OfficeConsumerConsumerCorporateHome Offic...,United StatesUnited StatesUnited StatesUnited ...,Fort WorthPhiladelphiaPhiladelphiaHoustonPortl...,TexasPennsylvaniaPennsylvaniaTexasOregonIllino...,32609300,CentralEastEastCentralWestCentralWestSouthWest...,Office SuppliesOffice SuppliesOffice SuppliesO...,36140.6130,2456,452.40,-38510.4964
Bookcases,Standard ClassStandard ClassStandard ClassSeco...,ConsumerHome OfficeCorporateHome OfficeConsume...,United StatesUnited StatesUnited StatesUnited ...,PhiladelphiaHoustonMedinaColumbusNew York City...,PennsylvaniaTexasOhioOhioNew YorkTexasTexasCal...,6423506,EastCentralEastEastEastCentralCentralWestEastE...,FurnitureFurnitureFurnitureFurnitureFurnitureF...,48072.7408,422,37.99,-12152.2060
Chairs,Second ClassStandard ClassStandard ClassStanda...,ConsumerHome OfficeHome OfficeConsumerHome Off...,United StatesUnited StatesUnited StatesUnited ...,PhiladelphiaHoustonChicagoMemphisHoustonLos An...,PennsylvaniaTexasIllinoisTennesseeTexasCalifor...,15008025,EastCentralCentralSouthCentralWestCentralEastS...,FurnitureFurnitureFurnitureFurnitureFurnitureF...,91988.4560,876,61.40,-9880.8413
Fasteners,Standard ClassFirst ClassStandard ClassStandar...,CorporateHome OfficeHome OfficeConsumerCorpora...,United StatesUnited StatesUnited StatesUnited ...,ToledoPhiladelphiaSpringfieldPhiladelphiaPhila...,OhioPennsylvaniaOregonPennsylvaniaPennsylvania...,701930,EastEastWestEastEastWestWestEastWestCentralCen...,Office SuppliesOffice SuppliesOffice SuppliesO...,149.2800,55,2.40,-33.1952
Furnishings,First ClassFirst ClassSecond ClassStandard Cla...,CorporateCorporateConsumerConsumerConsumerCons...,United StatesUnited StatesUnited StatesUnited ...,RichardsonHoustonHoustonAuroraChicagoChicagoCh...,TexasTexasTexasColoradoIllinoisIllinoisIllinoi...,10970913,CentralCentralCentralWestCentralCentralCentral...,FurnitureFurnitureFurnitureFurnitureFurnitureF...,12845.8440,597,88.60,-6490.9134
Machines,Standard ClassStandard ClassFirst ClassSecond ...,ConsumerCorporateConsumerCorporateCorporateCor...,United StatesUnited StatesUnited StatesUnited ...,San AntonioMedinaDublinHoustonHoustonPhiladelp...,TexasOhioOhioTexasTexasPennsylvaniaNorth Carol...,2236261,CentralEastEastCentralCentralEastSouthSouthSou...,TechnologyTechnologyTechnologyTechnologyTechno...,72456.2530,157,25.60,-30118.6682
Phones,First ClassStandard ClassFirst ClassSecond Cla...,CorporateCorporateConsumerConsumerConsumerCons...,United StatesUnited StatesUnited StatesUnited ...,ColumbusMedinaPhiladelphiaPhiladelphiaLos Ange...,OhioOhioPennsylvaniaPennsylvaniaCaliforniaOreg...,6105294,EastEastEastEastWestWestEastEastEastEastEastEa...,TechnologyTechnologyTechnologyTechnologyTechno...,35797.8400,476,46.60,-7530.6235
Storage,Standard ClassFirst ClassStandard ClassStandar...,ConsumerHome OfficeConsumerCorporateCorporateC...,United StatesUnited StatesUnited StatesUnited ...,MemphisChicagoSan AntonioChicagoCincinnatiAust...,TennesseeIllinoisTexasIllinoisOhioTexasTexasNo...,8606475,SouthCentralCentralCentralEastCentralCentralSo...,Office SuppliesOffice SuppliesOffice SuppliesO...,37869.0720,569,32.20,-6426.3038
Supplies,Second ClassSecond ClassStandard ClassStandard...,ConsumerCorporateHome OfficeConsumerCorporateC...,United StatesUnited StatesUnited StatesUnited ...,NewarkTamaracPhoenixPhiladelphiaChicagoDallasB...,OhioFloridaArizonaPennsylvaniaIllinoisTexasTex...,1761430,EastSouthWestEastCentralCentralCentralEastCent...,Office SuppliesOffice SuppliesOffice SuppliesO...,14067.1760,110,6.60,-3015.6219
Tables,Standard ClassStandard ClassFirst ClassStandar...,ConsumerConsumerConsumerHome OfficeHome Office...,United StatesUnited StatesUnited StatesUnited ...,Fort LauderdaleBloomingtonDenverTampaTampaChic...,FloridaIllinoisColoradoFloridaFloridaIllinoisI...,10224004,SouthCentralWestSouthSouthCentralCentralWestEa...,FurnitureFurnitureFurnitureFurnitureFurnitureF...,104978.5460,757,74.15,-32412.1483

##### * we can observe that there are more loss in the "Binders category", "machine category", and "tables category"
##### * Binders category are getting the more sold, so giving even less discount may lead to high loss
##### * Therefore its better to give discounts where there is less sale so as to increase the sale of the products and normaliza discount rate.

In [8]:
loss_df['Sub-Category'].value_counts()

Sub-Category
Binders        613
Chairs         235
Tables         203
Furnishings    167
Storage        161
Phones         136
Bookcases      109
Accessories     91
Appliances      67
Machines        44
Supplies        33
Fasteners       12
Name: count, dtype: int64

In [9]:
loss_df.groupby(by='City').sum().sort_values('Profit',ascending=True).head(10)

,Ship Mode,Segment,Country,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
City,,,,,,,,,,,,
Philadelphia,Second ClassStandard ClassStandard ClassStanda...,ConsumerConsumerConsumerConsumerCorporateConsu...,United StatesUnited StatesUnited StatesUnited ...,PennsylvaniaPennsylvaniaPennsylvaniaPennsylvan...,4783713,EastEastEastEastEastEastEastEastEastEastEastEa...,FurnitureFurnitureOffice SuppliesOffice Suppli...,ChairsBookcasesBindersBindersBindersPhonesChai...,70460.5510,892,115.30,-19590.7411
Houston,Standard ClassStandard ClassFirst ClassFirst C...,Home OfficeHome OfficeCorporateCorporateConsum...,United StatesUnited StatesUnited StatesUnited ...,TexasTexasTexasTexasTexasTexasTexasTexasTexasT...,14256474,CentralCentralCentralCentralCentralCentralCent...,FurnitureFurnitureOffice SuppliesFurnitureFurn...,BookcasesChairsBindersFurnishingsFurnishingsCh...,37640.7304,683,104.14,-14785.3668
Chicago,Standard ClassFirst ClassStandard ClassStandar...,Home OfficeHome OfficeHome OfficeHome OfficeCo...,United StatesUnited StatesUnited StatesUnited ...,IllinoisIllinoisIllinoisIllinoisIllinoisIllino...,9397492,CentralCentralCentralCentralCentralCentralCent...,FurnitureOffice SuppliesTechnologyOffice Suppl...,ChairsStorageAccessoriesBindersAppliancesFurni...,19910.0120,541,88.20,-11120.6271
San Antonio,Standard ClassStandard ClassStandard ClassStan...,ConsumerConsumerConsumerConsumerCorporateCorpo...,United StatesUnited StatesUnited StatesUnited ...,TexasTexasTexasTexasTexasTexasTexasTexasTexasT...,2580831,CentralCentralCentralCentralCentralCentralCent...,TechnologyOffice SuppliesFurnitureOffice Suppl...,MachinesStorageChairsAppliancesTablesChairsBin...,17395.1450,139,17.10,-7831.0254
Lancaster,Standard ClassSecond ClassStandard ClassStanda...,CorporateHome OfficeHome OfficeConsumerConsume...,United StatesUnited StatesUnited StatesUnited ...,PennsylvaniaOhioOhioPennsylvaniaOhioPennsylvan...,683904,EastEastEastEastEastEastEastEastEastEastEastEa...,Office SuppliesFurnitureTechnologyOffice Suppl...,BindersTablesPhonesSuppliesAccessoriesBindersP...,7699.2420,71,9.40,-7632.4946
Burlington,Same DayStandard ClassStandard ClassSame Day,CorporateHome OfficeConsumerCorporate,United StatesUnited StatesUnited StatesUnited ...,North CarolinaNorth CarolinaNorth CarolinaNort...,108868,SouthSouthSouthSouth,TechnologyOffice SuppliesFurnitureFurniture,MachinesBindersTablesTables,12044.8740,19,2.00,-5999.3318
Dallas,Second ClassStandard ClassStandard ClassStanda...,ConsumerConsumerCorporateConsumerConsumerConsu...,United StatesUnited StatesUnited StatesUnited ...,TexasTexasTexasTexasTexasTexasTexasTexasTexasT...,5487794,CentralCentralCentralCentralCentralCentralCent...,Office SuppliesOffice SuppliesOffice SuppliesO...,AppliancesSuppliesStorageBindersAppliancesBind...,9994.0562,280,39.30,-4208.5218
Jacksonville,Standard ClassStandard ClassStandard ClassFirs...,ConsumerConsumerCorporateConsumerCorporateCorp...,United StatesUnited StatesUnited StatesUnited ...,FloridaFloridaFloridaFloridaNorth CarolinaNort...,1237176,SouthSouthSouthSouthSouthSouthSouthSouthSouthS...,Office SuppliesTechnologyFurnitureOffice Suppl...,BindersAccessoriesTablesBindersMachinesBinders...,31146.2710,154,18.85,-4059.9857
New York City,Standard ClassFirst ClassSame DaySame DayFirst...,ConsumerConsumerConsumerConsumerConsumerConsum...,United StatesUnited StatesUnited StatesUnited ...,New YorkNew YorkNew YorkNew YorkNew YorkNew Yo...,400828,EastEastEastEastEastEastEastEastEastEastEastEa...,FurnitureFurnitureFurnitureFurnitureFurnitureF...,BookcasesBookcasesTablesTablesTablesTablesBook...,19533.8020,132,12.20,-3966.0226
Louisville,Second ClassStandard ClassStandard ClassStanda...,ConsumerHome OfficeHome OfficeHome OfficeHome ...,United StatesUnited StatesUnited StatesUnited ...,ColoradoColoradoColoradoColoradoColoradoColora...,640216,WestWestWestWestWestWestWestWest,FurnitureOffice SuppliesTechnologyOffice Suppl...,TablesBindersMachinesBindersBindersBindersBook...,2884.7840,35,4.90,-3694.1045

##### * The above list shows the top 10 cities with high loss

In [15]:
loss_df.sort_values(['Sales'].groupby(by='Category').mean())

AttributeError: 'list' object has no attribute 'groupby'

In [10]:
superstore_df.groupby(['State']).sum()['Sales'].nsmallest(10)

State
North Dakota             919.910
West Virginia           1209.824
Maine                   1270.530
South Dakota            1315.560
Wyoming                 1603.136
District of Columbia    2865.020
Kansas                  2914.310
Idaho                   4382.486
Iowa                    4579.760
New Mexico              4783.522
Name: Sales, dtype: float64

In [13]:
superstore_df.sort_values(['Segment'],ascending=True).groupby('Segment').sum()

,Ship Mode,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Segment,,,,,,,,,,,,
Consumer,Second ClassStandard ClassStandard ClassStanda...,United StatesUnited StatesUnited StatesUnited ...,HendersonChicagoSan FranciscoSmyrnaLos Angeles...,KentuckyIllinoisCaliforniaGeorgiaCaliforniaNew...,288878609,SouthCentralWestSouthWestEastEastEastEastEastE...,FurnitureOffice SuppliesFurnitureOffice Suppli...,BookcasesPaperFurnishingsEnvelopesPaperPaperCh...,1.161401e+06,19521,820.91,134119.2092
Corporate,Second ClassStandard ClassFirst ClassSecond Cl...,United StatesUnited StatesUnited StatesUnited ...,HoustonSan FranciscoArlingtonChicagoPhiladelph...,TexasCaliforniaVirginiaIllinoisPennsylvaniaCal...,164536330,CentralWestSouthCentralEastWestWestSouthEastWe...,FurnitureTechnologyOffice SuppliesOffice Suppl...,ChairsPhonesStorageStorageEnvelopesBindersEnve...,7.061464e+05,11608,477.85,91979.1340
Home Office,Standard ClassStandard ClassSecond ClassStanda...,United StatesUnited StatesUnited StatesUnited ...,New York CityLos AngelesHendersonSan Francisco...,New YorkCaliforniaKentuckyCaliforniaFloridaNew...,98157713,EastWestSouthWestSouthEastWestCentralWestEastE...,FurnitureOffice SuppliesOffice SuppliesOffice ...,TablesArtEnvelopesBindersStoragePaperPaperPhon...,4.296531e+05,6744,262.33,60298.6785